version: "3.9"

networks:
  integration-tests:

services:
  postgres:
    image: postgres:14-alpine
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hangman_db
      PGPORT: 5433
    networks:
      - integration-tests
  build-db-relationships:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    environment:
      DATABASE_PORT: 5433
      DATABASE_HOST: postgres
      DATABASE_NAME: hangman_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_POOL_MIN: 2
      DATABASE_POOL_MAX: 10
    depends_on:
      - postgres
    command:
      [
        "./wait-for-it.sh",
        "postgres:5433",
        "--strict",
        "--timeout=300",
        "--",
        "./node_modules/knex/bin/cli.js",
        "migrate:latest",
      ]
    networks:
      - integration-tests
  test-integration:
    build:
      context: .
      dockerfile: Dockerfile.test-integration
    environment:
      DATABASE_PORT: 5433
      DATABASE_HOST: postgres
      DATABASE_NAME: hangman_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_POOL_MIN: 2
      DATABASE_POOL_MAX: 10
    depends_on:
      - postgres
      - build-db-relationships
    networks:
      - integration-tests